services:
  client:
    image: yamee/app-client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    image: yamee/app-server
    container_name: server
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
    driver: local
